[package]
name = "aoc-2022"
version = "0.1.0"
authors = ["Andrew Marquez <andy2mgcc@gmail.com>"]
edition = "2021"
default-run = "aoc-2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
